/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `employee_projects`;

DROP TABLE IF EXISTS `employee`;

DROP TABLE IF EXISTS `project`;

DROP TABLE IF EXISTS `employer`;

CREATE TABLE `employer` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY)
 ENGINE=InnoDB;

CREATE TABLE `project` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY)
 ENGINE=InnoDB;

CREATE TABLE `employee` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `first` TEXT NOT NULL,
  `last` TEXT NOT NULL,
  `employer` VARCHAR(255) NOT NULL
  /*
  CONSTRAINT `employee_employer_fk`
    FOREIGN KEY (`employer`)
    REFERENCES `employer` (`name`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `employee_projects` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  CONSTRAINT `employee_projects_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `employee` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `employee_projects_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `project` (`name`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `employee_projects` (`object_id`);

